# Generated by Django 4.1.13 on 2024-01-28 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Editor', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
